name: Trigger dash-apps Build

on:
  push:
    branches:
      - main

jobs:
  trigger-zulu:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Zulu workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"event_type": "compile"}' \
            https://api.github.com/repos/JulesBoissier/dash-apps/dispatches
